import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
thickness = 0.13

[cursor.style]
blinking = "Off"
shape    = "Beam"

[env]
TERM = "alacritty"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style  = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[mouse]
hide_when_typing = false

[scrolling]
history    = 10000
multiplier = 3

[window]
dynamic_padding = false
dynamic_title   = false
opacity         = 1.0
title           = "Alacritty"

[window.dimensions]
columns = 150
lines   = 45

[window.padding]
x = 3
y = 3
