[files.config]
src  = "alacritty.toml"
dest = ".config/alacritty/alacritty.toml"

[scripts.install-themes]
text = '''
if [ ! -d ~/.config/alacritty/themes ]; then
    git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
fi
'''

[scripts.macos-install]
text  = "brew install --cask alacritty"
hosts = ["macos"]

[scripts.arch-install]
text  = "sudo pacman -S alacritty --needed --noconfirm"
hosts = ["arch-vm"]
