[files.configs]
src  = "configs"
dest = ".config/nvim"

[scripts.macos-install]
text  = "brew install neovim"
hosts = ["macos"]

[scripts.arch-install]
text  = "sudo pacman -S neovim ripgrep --needed --noconfirm"
hosts = ["arch-vm"]
