imports = [
  "../modules/alacritty",
  "../modules/git",
  "../modules/starship",
  "../modules/zsh",
  "../modules/nvim",
  "../modules/nano",
  "../modules/fonts",
  # Arch specific
  "../modules/hyprland",
  "../modules/gnome",
]

[host]
name = "arch"
