imports = [
  # Alacritty
  "../modules/alacritty/arch/install.toml",
  "../modules/alacritty/config.toml",
  # Git & GitHub
  "../modules/git/config.toml",
  # Starship
  "../modules/starship/arch/install.toml",
  "../modules/starship/config.toml",
  # Zsh
  "../modules/zsh/arch/install.toml",
  "../modules/zsh/config.toml",
  # Neovim
  "../modules/nvim/arch/install.toml",
  "../modules/nvim/config.toml",
]
