imports = [
  "../modules/software",
  "../modules/alacritty",
  "../modules/git",
  "../modules/starship",
  "../modules/zsh",
  "../modules/nvim",
  "../modules/nano",
  "../modules/fonts",
  # MacOS specific
  "../modules/skhd",
]

[host]
name = "macos"
