imports = [
  # Alacritty
  "../modules/alacritty/macos/install.toml",
  "../modules/alacritty/config.toml",
  # Git & GitHub
  "../modules/git/config.toml",
  # Starship
  "../modules/starship/macos/install.toml",
  "../modules/starship/config.toml",
  # Zsh
  "../modules/zsh/macos/install.toml",
  "../modules/zsh/config.toml",
  # Neovim
  "../modules/nvim/macos/install.toml",
  "../modules/nvim/config.toml",
]
