[scripts.macos-install]
text = '''
brew tap homebrew/cask-fonts
brew install font-jetbrains-mono-nerd-font
'''
hosts = ["macos"]

[scripts.arch-install]
text  = "sudo pacman -S ttf-jetbrains-mono-nerd --needed --noconfirm"
hosts = ["arch-vm"]
