[files.config]
src  = "starship.toml"
dest = ".config/starship.toml"

[scripts.macos-install]
text  = "brew install starship"
hosts = ["macos"]

[scripts.arch-install]
text  = "sudo pacman -S starship --needed --noconfirm"
hosts = ["arch-vm"]
