[arch.scripts.install_software]
text = '''
sudo pacman -Syu --noconfirm
sudo pacman -S --needed --noconfirm which gcc fastfetch firefox
'''
stage = -1

[macos.scripts.install_software]
text = '''
brew update && brew upgrade
brew install fastfetch
'''
stage = -1
