[scripts.arch-install-software]
text = '''
sudo pacman -S --needed --noconfirm which fastfetch firefox
'''
stage = -1
hosts = ["arch-vm"]

[scripts.macos-install-software]
text = '''
brew install fastfetch
'''
stage = -1
hosts = ["macos"]
