[files.config]
src   = "hyprland.conf"
dest  = ".config/hypr/hyprland.conf"
hosts = ["arch-vm"]

[scripts.install]
text = '''
sudo pacman -S --needed --noconfirm hyprland dolphin wofi hyprpaper 
'''
hosts = ["arch-vm"]
