[files.config]
src   = "hyprland.conf"
dest  = ".config/hypr/hyprland.conf"
hosts = ["arch-vm"]

[scripts.install]
text = '''
sudo pacman -S hyprland kitty gtk3 --needed --noconfirm
'''
hosts = ["arch-vm"]
